name: 'Test Scanner'
on: [workflow_dispatch]

permissions:
  contents: read

jobs:
  local-scanner-testing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: Sample Scanner
        uses: pnp/action-sample-scanner@main
        with:
          dirs: '["testing/samples"]'
          token: ${{ secrets.GITHUB_TOKEN }}
          
